cargo build --release

BIN_NAME=quote

PWD=$(pwd)
SOURCE_BINARY_PATH=$PWD/target/release/quote
DESTINATION_BIN_FOLDER=$BIN_ARBITRAGE_DIR_PATH

cp -r $SOURCE_BINARY_PATH $DESTINATION_BIN_FOLDER/$BIN_NAME